const ACTION_TYPES = {
  SET_STORIES: 'SET_STORIES',
  SET_ACTIVE_STORY: 'SET_ACTIVE_STORY',
  SET_ACTIVE_USER_STORY: 'SET_ACTIVE_USER_STORY',
  SET_PROGRESS: 'SET_PROGRESS',
  SET_PAUSED: 'SET_PAUSED',
  SET_IMAGE_LOADING: 'SET_IMAGE_LOADING',
  NEXT_STORY: 'NEXT_STORY',
  PREVIOUS_STORY: 'PREVIOUS_STORY',
  CLOSE_STORY: 'CLOSE_STORY',
  RESET_PROGRESS: 'RESET_PROGRESS'
};

export { ACTION_TYPES };